service: shop-service-aws-v5

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  #  stage: dev
  environment:
    PRODUCTS_TABLE: ${env:PRODUCTS_TABLE}
    STOCKS_TABLE: ${env:STOCKS_TABLE}
    SNS_ARN:
      Ref: SNSTopic
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - Fn::GetAtt: [SQSQueue, Arn]
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: { Ref: "SNSTopic" }
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/*"
        - Effect: Allow
          Action:
            - sns:*
          Resource: "arn:aws:sns:us-east-1:345840731224:createProductTopic"

plugins:
  - serverless-auto-swagger
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
  autoswagger:
    title: "Product service API"
    typefiles: "./src/types/product.ts"
    basePath: "/dev"
    apiType: http
  dotenv:
    basePath: ./

package:
  exclude:
    - node_modules/**

functions:
  getProductById:
    handler: src/handlers/getProductById.getProductById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  getProductsList:
    handler: src/handlers/getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  createProduct:
    handler: src/handlers/createProduct.createProduct
    events:
      - http:
          path: /products
          method: put
          cors: true
  catalogBatchProcess:
    handler: src/handlers/catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
          batchSize: 5
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: { Ref: "SNSTopic" }

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: aaronmqz.mx@gmail.com
        Protocol: email
        TopicArn: !Ref SNSTopic
    SNSVIPSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        Endpoint: aaron-con-a@hotmail.com
        TopicArn: !Ref SNSTopic
        FilterPolicyScope: MessageAttributes
        FilterPolicy: '{"title": ["VIP"]}'
